FROM golang:alpine as builder
RUN mkdir /build
ADD . /build
WORKDIR /build

RUN apk add gcc libc-dev
## Add this go mod download command to pull in any dependencies
ENV GO111MODULE=on
RUN go mod download
## Our project will now successfully build with the necessary go libraries included.
RUN go build -o main .

FROM alpine
RUN adduser -S -D -H -h /app appuser
USER appuser
COPY --from=builder /build/main /app/
COPY --from=builder /build/books.db /
WORKDIR /app
## Our start command which kicks off
## our newly created binary executable
CMD ["/app/main"]
